# Generated by Django 5.1.1 on 2024-09-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('contact', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('licence', models.CharField(max_length=90)),
                ('vehicle', models.CharField(max_length=90)),
                ('vehicletype', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AID.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('contact', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('image', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AID.login_table')),
            ],
        ),
    ]
