# Generated by Django 5.1.1 on 2024-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AID', '0002_remove_driver_vehicle_remove_driver_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.FileField(default='sample.png', upload_to=''),
            preserve_default=False,
        ),
    ]
