# Generated by Django 5.1.1 on 2024-09-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AID', '0006_driver_latitude_driver_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AID.driver')),
            ],
        ),
    ]
