# Generated by Django 5.1.1 on 2024-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AID', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
