# Generated by Django 5.1.1 on 2024-10-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AID', '0009_chat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_loc', models.CharField(max_length=90)),
                ('To_loc', models.CharField(max_length=90)),
                ('passengers', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AID.driver')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AID.user')),
            ],
        ),
    ]
