# Generated by Django 5.1.1 on 2024-10-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AID', '0010_bookingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='DRIVER',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='AID.driver'),
            preserve_default=False,
        ),
    ]
